// Generated by CoffeeScript 2.4.1
(function() {
  var counterPlus, getToday, populateStorage;

  window.onload = function() {
    'use strict';
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('./sw.js').then(function(registration) {
        console.log('Service Worker Registered', registration);
      }).catch(function(err) {
        console.log('Service Worker Failed to Register', err);
      });
    }
  };

  this.successClicker = function() {
    if (localStorage.hasOwnProperty('successToday')) {
      if (localStorage.successToday < getToday()) {
        localStorage.successToday = getToday();
        counterPlus();
      } else {
        console.log('You have allready succeeded today!');
      }
    } else {
      populateStorage();
    }
  };

  populateStorage = function() {
    localStorage.successToday = getToday();
    return localStorage.successCounter = 1;
  };

  counterPlus = function() {
    if (localStorage.successCounter > 0) {
      localStorage.successCounter++;
    } else {
      console.log('That should not have happened.');
    }
  };

  getToday = function() {
    var date, day, month, todayInt, year;
    date = new Date();
    year = date.getFullYear();
    month = ((date.getMonth() + 1 < 10) ? '0' : '') + (date.getMonth() + 1);
    day = ((date.getDate() < 10) ? '0' : '') + date.getDate();
    todayInt = parseInt(year + month + day);
    return todayInt;
  };

}).call(this);
