// Generated by CoffeeScript 2.4.1
(function() {
  window.onload = function() {
    'use strict';
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('./sw.js');
    }
  };

}).call(this);
