// Generated by CoffeeScript 2.4.1
(function() {
  window.onload = function() {
    'use strict';
    if ('serviceWorker' in navigator) {
      return navigator.serviceWorker.register('./sw.js').then(function(registration) {
        console.log('Service Worker Registered', registration);
      }).catch(function(err) {
        console.log('Service Worker Failed to Register', err);
      });
    }
  };

}).call(this);
